# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: windows_vs2017_win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: WMIC CPU Get /Format:List
    displayName: cpu info
    
  - script: |
     dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild" /s /b
    
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_x64 -vcvars_ver=14.0
      where MSBuild.exe
      MSBuild.exe --version

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      python ./test_secret.py
    displayName: 'Run a multi-line script'
    env: 
      MYSECRET: $(pipeline-secret)
  
  - script: |
      pip install winregistry
      python ./test_registry.py
    displayName: 'Fetch some registry keys'     
    
  - script:
      dir "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\"
    displayName: Dir some things C:\Program Files (x86)
  
