# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      python3 ./test_secret.py
    displayName: 'Run a multi-line script'
    env: 
      MYSECRET: $(pipeline-secret)

- job: windows_vs2017_win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      python ./test_secret.py
    displayName: 'Run a multi-line script'
    env: 
      MYSECRET: $(pipeline-secret)

- job: windows_vs2015_win2012r2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      python ./test_secret.py
    displayName: 'Run a multi-line script'
    env: 
      MYSECRET: $(pipeline-secret)


