# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: env
    displayName: 'Print env variables'
  - script: echo "##vso[task.setvariable variable=NEED_CUDA;isOutput=true]1"
    name: ASDOutputs

- job: linux_cuda9
  dependsOn: linux
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(dependencies.linux.outputs['ASDOutputs.NEED_CUDA'], '1')
  steps:
  - script: env
    displayName: 'Print env variables'
  - script: sleep 100s
    displayName: 'Sleep'

- job: linux_cuda10
  dependsOn: linux
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(dependencies.linux.outputs['ASDOutputs.NEED_CUDA'], '1')
  steps:
  - script: env
    displayName: 'Print env variables'
  - script: sleep 100s
    displayName: 'Sleep'

