# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: win
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        from urllib.request import urlretrieve
        urlretrieve(
          'https://micromamba.snakepit.net/api/micromamba/win-64/latest',
          'micromamba.tar.bz2'
        )
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'micromamba.tar.bz2'
      cleanDestinationFolder: false
  - script: |
      set "MAMBA_ROOT_PREFIX=C:\conda"
      set "CONDA_PREFIX=C:\conda"
      Library\bin\micromamba.exe install python=3.6 conda-build conda "conda-forge-ci-setup=3" pip -c conda-forge
