# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: win
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: PythonScript@0
    displayName: Download conda-standalone
    inputs:
      scriptSource: 'inline'
      script: |
        from urllib.request import urlretrieve
        urlretrieve(
          'https://conda.anaconda.org/conda-forge/win-64/conda-standalone-4.9.2-h57928b3_2.tar.bz2',
          'conda-standalone.tar.bz2'
        )
  - task: ExtractFiles@1
    displayName: Extract conda-standalone
    inputs:
      archiveFilePatterns: 'conda-standalone.tar.bz2'
      cleanDestinationFolder: false
  - script: |
      mkdir C:\conda
      set "MAMBA_ROOT_PREFIX=C:\conda"
      set "CONDA_PREFIX=C:\conda"
      conda-standalone\conda.exe install --yes python=3.6 conda-build conda "conda-forge-ci-setup=3" pip -c conda-forge -c defaults
      ECHO ##vso[task.prependpath]C:\conda\Scripts
    displayName: Install conda, conda-build and build tools
  - script: |
      call activate base
      conda --version
